Update test10.yml

diff --git a/.github/workflows/test10.yml b/.github/workflows/test10.yml
--- a/.github/workflows/test10.yml
+++ b/.github/workflows/test10.yml
@@ -11,4 +11,5 @@ jobs:
       - name: Debug echo
         run: |
           filename="MY_FILE.TXT"
-          echo "::error::Filename $filename doesn't match possible files" && exit 2
+          echo "::error::Filename $filename doesn't match possible files"
+          exit 1
